<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('Delete image'); ?></h4>
            </div>
            <div class="modal-body">
                <?= $this->translate('Are you sure you want to delete this image?') ?>
            </div>
            <div class="modal-footer">
                <a href="<?php echo $this->url('admin/adminGallery', ['alias' => '']); ?>"
                   class="btn btn-danger"><?= $this->translate('Yes') ?></a>
                <a href="javascript:$('#myModal').modal('hide')" class="btn btn-default">
                    <?= $this->translate('No') ?>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="widget wred">
            <div class="widget-head">
                <div class="pull-left"><?php echo $this->translate('Manage images'); ?></div>
                <div class="pull-right">
                    <a href="<?php echo $this->url(
                        'admin/adminGallery/uploadAlbumImages', ['alias' => $this->alias, 'userId' => $this->userId]
                    ); ?>" type="button" class="btn btn-default btn-xs">
                        <span class="glyphicon glyphicon-plus"></span>
                        <?php echo $this->translate('Upload new images'); ?>
                    </a>
                    <a href="<?php echo $this->url(
                        'admin/adminGallery/userAlbums',
                        array('userId' => $this->userId)
                    ); ?>" type="button" class="btn btn-default btn-xs">
                        <span class="glyphicon glyphicon-arrow-left"></span>
                        <?php echo $this->translate('Back to albums'); ?>
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <div class="padd">
                    <?php if (!$this->albumImages) { ?>
                        <div class="alert alert-info"><?php echo $this->translate('No images in album'); ?></div>
                    <?php } else { ?>
                        <?php foreach ($this->albumImages as $image) { ?>
                            <div class="manage-image-container">
                                <div class="padd">
                                    <img src="<?php echo $image->getThumbUrl(); ?>" class="img-thumbnail">
                                    <?php echo $image->getName(); ?>
                                    <?php echo $image->getShortDescription(); ?>
                                    <a href="<?php echo $this->url(
                                        'admin/adminGallery/manageAlbumImage',
                                        ['imageAlias' => $image->getAlias(), 'albumAlias' => $this->alias, 'userId' => $this->userId]
                                    ) ?>" type="button" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                        <?php echo $this->translate('Edit image'); ?>
                                    </a>
                                    <a data-toggle="modal" href="#myModal" class="remove-item btn btn-default btn-sm"
                                       data-delete-url="<?php echo $this->url(
                                           'admin/adminGallery/deleteAlbumImage',
                                           ['imageAlias' => $image->getAlias(), 'albumAlias' => $this->alias, 'userId' => $this->userId, 'imageAlias' => $image->getAlias()]
                                       ) ?>">
                                        <i class="icon-remove"></i>
                                        <?php echo $this->translate('Delete image'); ?>
                                    </a>
                                </div>
                            </div>
                        <?php }
                    } ?>
                </div>
            </div>
        </div>
    </div>
</div>