<div class="row">
    <div class="col-md-12">
        <div class="widget wred">
            <div class="widget-head">
                <div class="pull-left"><?php echo $this->translate('manage_images'); ?></div>
                <div class="pull-right">
                    <a href="<?php echo $this->url('admin/adminGallery/uploadAlbumImages', ['alias' => $this->alias]); ?>" type="button" class="btn btn-default btn-xs">
                        <span class="glyphicon glyphicon-plus"></span>
                        <?php echo $this->translate('upload_new_images'); ?>
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <div class="padd">
                    <?php if (!$this->albumImages) { ?>
                        <div class="alert alert-info"><?php echo $this->translate('no_images_in_album'); ?></div>
                    <?php } ?>
                    <?php foreach ($this->albumImages as $image) { ?>
                        <div class="manage-image-container">
                            <div class="padd">
                                <img src="..." alt="..." class="img-thumbnail">
                                <?php echo $image->getName(); ?>
                                <?php echo $image->getShortDescription(); ?>
                                <a href="<?php echo $this->url(
                                    'admin/adminGallery/manageAlbumImage', ['alias' => $image->getAlias()]
                                ) ?>" type="button" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                    <?php echo $this->translate('edit_image'); ?>
                                </a>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>