<?php //TODO:commented out for now, couse php logic not done yet?>
<?php //$form = $this->editImageForm(); ?>
<div class="row">
    <div class="col-md-12">
        <?php
        /*echo $this->form()->openTag($form);
        echo $this->formRow($form->get('title'));
        echo $this->formRow($form->get('artist'));
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();*/
        ?>
    </div>
</div>
