<div class="row">
    <div class="col-md-12">
        <div class="widget wred">
            <div class="widget-head">
                <div class="pull-left"><?php echo $this->translate('Upload images'); ?></div>
                <div class="pull-right">
                    <a href="<?= $this->url(
                        'admin/adminGallery/manageAlbumImages', ['alias' => $this->alias, 'userId' => $this->userId]
                    ) ?>" type="button" class="btn btn-default btn-xs">
                        <span class="glyphicon glyphicon-arrow-left"></span>
                        <?php echo $this->translate('Back to album'); ?>
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <div class="padd">
                    <div id="progress">
                    </div>
                    <?php
                    $form = $this->uploadImageForm;
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formFileUploadProgress();
                    $fileElement = $form->get('uploadImageFile');
                    echo $this->formFile($fileElement);
                    echo $this->formRow($form->get('csrf'));
                    echo $this->formElementErrors($fileElement);
                    ?>
                    <div id="file-errors" class="help-block"></div> <?php
                    echo $this->formSubmit(
                        $form->get('uploadImageFormSubmit')->setAttribute('class', 'btn btn-primary')
                            ->setAttribute('value', $this->translate('Submit'))
                    );
                    echo $this->form()->closeTag($form);
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="loadedImages">
</div>

<script>
    var finishUploadUrl = '<?php echo $this->url('admin/adminGallery/finishImageUpload'); ?>';
</script>