<div class="row">
    <div class="col-md-12">
        <div class="widget wred">
            <div class="widget-head">
                <div class="pull-left"><?php echo $this->translate('upload_images'); ?></div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <div class="padd">
                    <div id="progress">
                    </div>
                    <?php
                    $form = $this->uploadImageForm;
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formFileUploadProgress();
                    $fileElement = $form->get('uploadImageFile');
                    echo $this->formFile($fileElement);
                    echo $this->formRow($form->get('csrf'));
                    echo $this->formElementErrors($fileElement);
                    ?>
                    <div id="file-errors" class="help-block"></div> <?php
                    echo $this->formSubmit(
                        $form->get('uploadImageFormSubmit')->setAttribute('class', 'btn btn-primary')
                            ->setAttribute('value', $this->translate('submit'))
                    );
                    echo $this->form()->closeTag($form);
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="loadedImages">
</div>

<script>
    var finishUploadUrl = '<?php echo $this->url('admin/adminGallery/finishImageUpload'); ?>';
</script>