<div class="row">
    <div class="col-md-12">
        <div class="widget wred">
            <div class="widget-head">
                <div class="pull-left"><?php echo $this->translate('upload_images'); ?></div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <div class="padd">
                    <div id="progress">
                    </div>
                    <?php
                    $form = $this->uploadImageForm;
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formFileUploadProgress();
                    $fileElement = $form->get('uploadImageFile');
                    echo $this->formFile($fileElement);
                    echo $this->formRow($form->get('csrf'));
                    echo $this->formElementErrors($fileElement);
                    ?>
                    <div id="file-errors" class="help-block"></div> <?php
                    echo $this->formSubmit(
                        $form->get('uploadImageFormSubmit')->setAttribute('class', 'btn btn-primary')
                            ->setAttribute('value', $this->translate('submit'))
                    );
                    echo $this->form()->closeTag($form);
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="loadedImages">
</div>

<script>
    var bar = $('#progress').uploadProgressBar();

    function hideErrors() {
        $('#file-errors').hide();
    }

    function showErrors(message) {
        $('#file-errors').show().html(message);
    }

    function hideFormElements() {
        $('#uploadImageFile').hide();
        $('#uploadImageFormSubmit').hide();
    }

    function showFormElements() {
        $('#uploadImageFile').show();
        $('#uploadImageFormSubmit').show();
    }

    var progressInterval;

    function showProgress(amount, message) {
        $('#progress').show();
        $('#progress .progress-bar').width(amount + '%');
        $('#progress > p').html(message);
        if (amount < 100) {
            $('#progress .progress')
                .addClass('active')
                .addClass('progress-info')
                .removeClass('progress-success');
        } else {
            $('#progress .progress')
                .removeClass('active')
                .removeClass('progress-info')
                .addClass('progress-success');
        }
    }

    function startProgress() {
        bar.uploadProgressBar( "option", "value", 0);
        bar.uploadProgressBar( "startProgress");
    }

    function loadImageDiv(url, id) {
        $('<div/>', {
            'class': 'row', html: getImageContainerHtml()
        }).hide().appendTo('#loadedImages').slideDown('slow');
    }

    function getImageContainerHtml() {
        var $col = $('<div/>', {
            class: 'col-md-12'
        });

        var $saveImageContainer = $('<div/>', {
            class: 'save-image-container'
        });

        var $padd = $('<div/>', {
            class: 'padd',
            text: 'image text'
        });

        var $checkButton = $('<button/>', {
            type: 'button',
            class: 'btn btn-default btn-xs pull-right save-image'
        });

        $checkButton.click(function() {
            $col.hide('slow');
        });

        var $iconSpan = $('<span/>', {
            class: 'glyphicon glyphicon-ok'
        });

        $checkButton.append($iconSpan);
        $padd.append($checkButton);
        $saveImageContainer.append($padd);
        $col.append($saveImageContainer);

        return $col;
    }

    $(function () {
        $('#uploadImageForm').on('submit', function (e) {
            e.preventDefault();

            if ($('#uploadImageFile').val() == '') {
                showErrors('No file(s) selected');
                return;
            }

            hideFormElements();
            hideErrors();

            $(this).ajaxSubmit({
                success: function (response, statusText, xhr, $form) {
                    console.log(response);
                    $.each(response.images, function (index, value) {
                        loadImageDiv(value.url, value.id);
                    });
                    showFormElements();
                },
                error: function (a, b, c) {
                    console.log(a, b, c);
                    showFormElements();
                }
            });
            startProgress();
        });
    });
</script>