<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('Delete album'); ?></h4>
            </div>
            <div class="modal-body">
                <?= $this->translate('Are you sure you want to delete this album?') ?>
            </div>
            <div class="modal-footer">
                <a href="<?php echo $this->url('admin/adminGallery', ['alias' => '']); ?>"
                   class="btn btn-danger"><?= $this->translate('Yes') ?></a>
                <a href="javascript:$('#myModal').modal('hide')" class="btn btn-default">
                    <?= $this->translate('No') ?>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="widget wred">
            <div class="widget-head">
                <div class="pull-left"> <?= $this->translate('User albums') ?></div>
                <div class="pull-right">
                    <a href="<?=
                    $this->url(
                        'admin/adminGallery', ['userId' => $this->userId]
                    ) ?>" type="button" class="btn btn-default btn-xs">
                        <span class="glyphicon glyphicon-arrow-left"></span>
                        <?php echo $this->translate('Back to users'); ?>
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <table class="table table-bordered ">
                    <?php if ($this->galleryAlbums) { ?>
                        <thead>
                        <tr>
                            <th>#</th>
                            <th><?php echo $this->translate('Album name') ?></th>
                            <th><?php echo $this->translate('Manage album images') ?></th>
                            <th><?php echo $this->translate('Album actions') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->galleryAlbums as $key => $galleryAlbum) { ?>
                            <tr>
                                <td><?php echo $key + 1; ?></td>
                                <td><?php echo $galleryAlbum->getName(); ?></td>
                                <td>
                                    <a href="<?php echo $this->url(
                                        'admin/adminGallery/manageAlbumImages',
                                        ['alias' => $galleryAlbum->getAlias(), 'userId' => $this->userId]
                                    ); ?>">
                                        <?php echo
                                            $this->translate('Manage album images') . ' ('
                                            . $galleryAlbum->getImagesCount()
                                            . ')'; ?>
                                </td>
                                <td>
                                    <a href="<?php echo $this->url(
                                        'admin/adminGallery/editAlbum',
                                        array('alias' => $galleryAlbum->getAlias(), 'userId' => $this->userId)
                                    ); ?>">
                                        <button class="btn btn-xs btn-warning"><i class="icon-pencil"></i></button>
                                    </a>
                                    <a data-toggle="modal" href="#myModal" class="remove-item btn btn-danger btn-xs"
                                       data-delete-url="<?php echo $this->url(
                                           'admin/adminGallery/deleteAlbum',
                                           array('alias' => $galleryAlbum->getAlias(), 'userId' => $this->userId)
                                       ); ?>">
                                        <i class="icon-remove"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    <?php
                    } else {
                        ?>
                        <div class="empty-content"><?php echo $this->translate('No albums found'); ?></div>
                    <?php } ?>
                </table>
            </div>
            <div class="widget-foot">
                <div class="pagination pull-left">
                    <a href="<?php echo $this->url('admin/adminGallery/addAlbum', ['userId' => $this->userId]); ?>">
                        <button class="btn btn-default"><?php echo $this->translate('Add album'); ?></button>
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
