<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">

    <?php echo $this->headTitle($this->translate('admin_login_title'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?php echo $this->headLink()->appendStylesheet($this->basePath() . '/admin-assets/css/bootstrap.css')
        ->appendStylesheet($this->basePath() . '/admin-assets/css/font-awesome.css')
        ->appendStylesheet($this->basePath() . '/admin-assets/css/jquery-ui.css')
        ->appendStylesheet($this->basePath() . '/admin-assets/css/style.css')
        ->appendStylesheet($this->basePath() . '/admin-assets/css/responsive-480.css')
        ->headLink(array('rel' => 'shortcut icon', 'href' => 'data:image/x-icon;,', 'type' => 'image/x-icon')) ?>
</head>
<body>
<?php echo $this->content ?>
<!-- HTML5 Support for IE -->
<!--[if lt IE 9]>
<script src="/admin-assets/js/html5shim.js"></script>
<![endif]-->
<?php echo $this->headScript()->appendFile($this->basePath() . '/admin-assets/js/jquery.js')
    ->appendFile($this->basePath() . '/admin-assets/js/bootstrap.js')
    ->appendFile($this->basePath() . '/admin-assets/js/jquery-ui-1.10.2.custom.min.js')
?>
</body>
</html>
