<?php
$form = $this->albumForm;
$form->prepare();
?>
<div class="row">
    <div class="col-md-12">
        <div class="widget wred">
            <div class="widget-head">
                <div class="pull-left"><?php echo $this->translate($this->action); ?></div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <div class="padd">
                    <?php echo $this->form()->openTag($form); ?>
                    <div class='form-group'>
                        <label for="name"><?php echo $this->translate('Album name') ?></label>
                        <?php echo $this->formRow($form->get('name')->setAttribute('class', 'form-control')); ?>
                    </div>
                    <div class="form-group col-lg-10 padding-left-0 padding-right-0">
                        <label for="location"><?php echo $this->translate('Album location') ?></label>
                        <?php echo $this->formRow($form->get('location')->setAttribute('class', 'form-control')); ?>
                    </div>
                    <div class="form-group col-lg-2 padding-right-0">
                        <label></label>
                        <div id="get-location" class="btn btn-warning form-control">
                            <?php echo $this->translate(
                                'Set location on map'
                            ); ?></div>
                    </div>
                    <div id="map-canvas"></div>
                    <div class="form-group">
                        <label for="shortDescription"><?php echo $this->translate('Album short description') ?></label>
                        <?php echo $this->formRow(
                            $form->get('shortDescription')->setAttribute('class', 'form-control')
                        ); ?>
                    </div>
                    <div class="form-group">
                        <label for="fullDescription"><?php echo $this->translate('Album full description') ?></label>
                        <?php echo $this->formRow(
                            $form->get('fullDescription')->setAttribute('class', 'form-control')
                        ); ?>
                    </div>
                    <div class="form-group">
                        <label for="isPublic"><?php echo $this->translate('Is album public') ?></label>
                        <?php echo $this->formRow($form->get('isPublic')); ?>
                    </div>
                    <?php echo $this->formRow($form->get('locationLat')); ?>
                    <?php echo $this->formRow($form->get('locationLng')); ?>
                    <?php echo $this->formRow($form->get('csrf')); ?>
                    <?php echo $this->formRow(
                        $form->get('addAlbumFormSubmit')->setAttribute('class', 'btn btn-success')->setAttribute(
                            'value', $this->translate('add')
                        )
                    ); ?>
                    <?php echo $this->form()->closeTag($form); ?>
                </div>
            </div>
        </div>
    </div>
</div>