<div class="row">
    <div class="col-md-12">
        <div class="widget wred">
            <div class="widget-head">
                <div class="pull-left"> <?php echo $this->translate('gallery_users') ?></div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="widget-content">
                <table class="table  table-bordered ">
                    <?php if ($this->users) { ?>
                        <thead>
                        <tr>
                            <th>#</th>
                            <th><?php echo $this->translate('user_email') ?></th>
                            <th><?php echo $this->translate('user_name') ?></th>
                            <th><?php echo $this->translate('user_albums_count') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->users as $key => $user) { ?>
                            <tr>
                                <td><?php echo $key + 1; ?></td>
                                <td><?php echo $user->getEmail(); ?></td>
                                <td><?php echo $user->getFirstName() . ' ' . $user->getLastName(); ?></td>
                                <td><a href="<?php echo $this->url(
                                        'admin/adminGallery/userAlbums',
                                        array('userId' => $user->getId())
                                    ); ?>"><?php echo
                                            $this->translate('manage_user_albums') . ' (' . $user->getAlbumsCount()
                                            . ')'; ?>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    <?php
                    } else {
                        ?>
                        <div class="empty-content"><?php echo $this->translate('no_users_found'); ?></div>
                    <?php } ?>
                </table>
            </div>
            <div class="widget-foot">
                <ul class="pagination pull-right">
                    <li><a href="#">Prev</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">Next</a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>