<div class="row">
    <div class="col-md-12">
        <div class="widget wred">
            <div class="widget-head">
                <span class="pull-left"> <?php echo $this->translate('Gallery users') ?></span>
                <div class="clearfix"></div>
            </div>

            <div class="widget-content">
                <table class="table  table-bordered ">
                    <?php if ($this->users) { ?>
                        <thead>
                        <tr>
                            <th>#</th>
                            <th><?php echo $this->translate('User email address') ?></th>
                            <th><?php echo $this->translate('Username') ?></th>
                            <th><?php echo $this->translate('User albums count') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->users as $key => $user) { ?>
                            <tr>
                                <td><?php echo $key + 1; ?></td>
                                <td><?php echo $user->getEmail(); ?></td>
                                <td><?php echo $user->getUserName(); ?></td>
                                <td>
                                    <a href="<?php echo $this->url(
                                        'admin/adminGallery/userAlbums',
                                        array('userId' => $user->getId())
                                    ); ?>">
                                        <?php echo
                                            $this->translate('Manage user albums') . ' (' . $user->getAlbumsCount()
                                            . ')'; ?>
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    <?php
                    } else {
                        ?>
                        <div class="empty-content"><?php echo $this->translate('No users found'); ?></div>
                    <?php } ?>
                </table>
            </div>
        </div>
    </div>
</div>