<?php
$form = $this->loginForm;
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
    <div class="admin-form">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- Widget starts -->
                    <div class="widget wred">
                        <!-- Widget head -->
                        <div class="widget-head">
                            <i class="icon-lock"></i> <?php echo $this->translate('login') ?>
                        </div>

                        <div class="widget-content">
                            <div class="padd">
                                <?php if (!empty($this->error)): ?>
                                    <div class="alert alert-error"><?php echo $error ?></div>
                                <?php endif; ?>
                                <div class="form-group">
                                    <label for="usernameInput"><?php echo $this->translate('username') ?></label>
                                    <?php echo $this->formRow(
                                        $form->get('loginFormUsername')->setAttribute('class', 'form-control')
                                    ); ?>
                                </div>
                                <div class="form-group">
                                    <label for="passwordInput"><?php echo $this->translate('password') ?></label>
                                    <?php echo $this->formRow(
                                        $form->get('loginFormPassword')->setAttribute('class', 'form-control')
                                    ); ?>
                                </div>
                                <?php echo $this->formSubmit(
                                    $form->get('loginFormSubmit')->setAttribute('class', 'btn btn-success')
                                        ->setAttribute('value', $this->translate('login'))
                                ); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php echo $this->form()->closeTag($form); ?>