<?php
$form = $this->loginForm;
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
    <div class="admin-form">
        <div class="widget wred">
            <div class="widget-head">
                <i class="icon-lock"></i> <?php echo $this->translate('login') ?>
            </div>
            <div class="widget-content">
                <div class="padd">
                    <?php if (!empty($this->error)): ?>
                        <div class="alert alert-error"><?php echo $this->error ?></div>
                    <?php endif; ?>
                    <div class="form-group">
                        <label for="usernameInput"><?php echo $this->translate('username') ?></label>
                        <?php echo $this->formRow(
                            $form->get('loginFormEmail')->setAttribute('class', 'form-control')
                        ); ?>
                    </div>
                    <div class="form-group">
                        <label for="passwordInput"><?php echo $this->translate('password') ?></label>
                        <?php echo $this->formRow(
                            $form->get('loginFormPassword')->setAttribute('class', 'form-control')
                        ); ?>
                    </div>
                    <?php echo $this->formRow($form->get('csrf')); ?>
                    <?php echo $this->formSubmit(
                        $form->get('loginFormSubmit')->setAttribute('class', 'btn btn-success')
                            ->setAttribute('value', $this->translate('Login'))
                    ); ?>
                </div>
            </div>
        </div>
    </div>
<?php echo $this->form()->closeTag($form); ?>