<?php
if ($this->success) {
    ?>
    <div class="alert alert-success"><?php echo $this->success; ?></div>
<?php
} else {
    if ($this->error) {
        ?>
        <div class="alert alert-danger"><?php echo $this->error; ?></div>
    <?php } ?>
    <?php
    $form = $this->registerForm;
    $form->setAttribute('action', $this->url('home/register'));
    $form->prepare();
    echo $this->form()->openTag($form); ?>
    <div class='form-group'>
        <label for="email"><?php echo $this->translate('email'); ?></label>
        <?php echo $this->formRow($form->get('email')->setAttribute('class', 'form-control')); ?>
    </div>
    <div class="form-group">
        <label for="firstName"><?php echo $this->translate('first_name'); ?></label>
        <?php echo $this->formRow($form->get('firstName')->setAttribute('class', 'form-control')); ?>
    </div>
    <div class="form-group">
        <label for="lastName"><?php echo $this->translate('last_name'); ?></label>
        <?php echo $this->formRow($form->get('lastName')->setAttribute('class', 'form-control')); ?>
    </div>
    <div class="form-group">
        <label for="password"><?php echo $this->translate('password'); ?></label>
        <?php echo $this->formRow($form->get('password')->setAttribute('class', 'form-control')); ?>
    </div>
    <div class="form-group">
        <label for="confirmPassword"><?php echo $this->translate('confirm_password'); ?></label>
        <?php echo $this->formRow($form->get('confirmPassword')->setAttribute('class', 'form-control')); ?>
    </div>
    <?php echo $this->formRow($form->get('csrf')); ?>
    <?php echo $this->formRow(
        $form->get('userRegisterFormSubmit')->setAttribute('class', 'btn btn-default')->setAttribute(
            'value', $this->translate('register')
        )
    ); ?>
    <?php echo $this->form()->closeTag($form);
}