<?php echo $this->doctype(); ?>
<?php
$sm = $this->getHelperPluginManager()->getServiceLocator();
$router = $sm->get('router');
$request = $sm->get('request');
$routeMatch = $router->match($request);
$authenticationService = $sm->get('Zend\Authentication\AuthenticationService');
?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('NFQ ' . $this->translate('akademija'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(
        array('rel'  => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
              'href' => $this->basePath() . '/img/favicon.ico')
    )
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/lightbox.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/responsive.css')?>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img
                    src="<?php echo $this->basePath('img/nfq-logo.png') ?>"
                    alt="NFQ akademija"/>&nbsp;<?php echo $this->translate('NFQ akademija') ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="<?php if (isset($routeMatch) && $routeMatch->getMatchedRouteName() == 'home') {
                    echo 'active';
                } ?>">
                    <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
                </li>
                <?php if ($authenticationService->hasIdentity()) { ?>
                    <li class="<?php if (isset($routeMatch) && $routeMatch->getMatchedRouteName() == 'home/gallery') {
                        echo 'active';
                    } ?>"><a href="<?php echo $this->url(
                            'home/gallery', ['userName' => $authenticationService->getIdentity()->getUserName()]
                        ) ?>"><?php echo $this->translate(
                                'My gallery'
                            ) ?></a>
                    </li>
                <?php } ?>
            </ul>
            <?php
            if (!$authenticationService->hasIdentity()) {
                $form = $this->loginForm;
                $form->setAttribute('class', 'navbar-form navbar-right')
                    ->setAttribute('action', $this->url('home/login'));
                $form->prepare();
                echo $this->form()->openTag($form); ?>
                <div class='form-group'>
                    <?php echo $this->formRow($form->get('loginFormEmail')->setAttribute('class', 'form-control')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formRow(
                        $form->get('loginFormPassword')->setAttribute('class', 'form-control')
                    ); ?>
                </div>
                <?php echo $this->formRow($form->get('csrf')); ?>
                <?php echo $this->formRow(
                    $form->get('loginFormSubmit')->setAttribute('class', 'btn btn-default')->setAttribute(
                        'value', $this->translate('login')
                    )
                ); ?>
                <a href="<?php echo $this->url('home/register'); ?>"
                   class="btn btn-default"><?php echo $this->translate('register'); ?></a>
                <?php echo $this->form()->closeTag($form);
            } else {
                ?>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo
                                $this->translate('Signed in as') . ' ' . $authenticationService->getIdentity()
                                    ->getEmail(); ?> <b class="caret"></b></a>
                        <ul class="dropdown-menu" role="menu">
                            <li class="divider"></li>
                            <li>
                                <a href="<?php echo $this->url('home/logout'); ?>"><?php echo $this->translate(
                                        'logout'
                                    ); ?>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <?php

                $formSearch = $this->searchForm;
                $formSearch->setAttribute('class', 'navbar-form navbar-right')
                    ->setAttribute('action', $this->url('home/search'));
                $formSearch->prepare();
                echo $this->form()->openTag($formSearch); ?>
                <div class='form-group'>
                    <?php echo $this->formRow(
                        $formSearch->get('searchFormWords')->setAttribute('class', 'form-control')
                    ); ?>
                </div>
                <?php echo $this->formRow($formSearch->get('csrf')); ?>
                <div class="form-group">
                    <?php echo $this->formRow(
                        $formSearch->get('searchFormSubmit')->setAttribute('class', 'btn btn-default btn-sm')
                            ->setAttribute('value', 'search')
                    ); ?>
                </div>
                <?php echo $this->form()->closeTag($formSearch);
            }
            ?>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; <?php echo date('Y') ?> by Amandas Šukionis. <?php echo $this->translate(
                'All rights reserved.'
            ) ?></p>
    </footer>
</div>
<!-- Scripts -->
<script>(function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/lt_LT/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
<?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/js/getAlbumLocation.js')
    ->prependFile($this->basePath() . '/js/deleteUrl.js')
    ->prependFile($this->basePath() . '/js/addTags.js')
    ->prependFile($this->basePath() . '/js/upvote-downvote.js')
    ->prependFile($this->basePath() . '/js/uploadImages.js')
    ->prependFile($this->basePath() . '/js/share.js')
    ->prependFile($this->basePath() . '/js/uploadProgressBar.js')
    ->prependFile($this->basePath() . '/js/lightbox-2.6.min.js')
    ->prependFile($this->basePath() . '/js/jquery.form.js')
    ->prependFile("https://maps.googleapis.com/maps/api/js?key=AIzaSyCYVqiIopFC0zpXH6pOYcdPq0bjOJY6wV8&sensor=false")
    ->prependFile($this->basePath() . '/admin-assets/js/jquery-ui-1.10.2.custom.min.js')
    ->prependFile($this->basePath() . '/js/jquery.min.js')
    ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
</body>
</html>
