<div class="row image-page">
    <h1><?=$this->translate('Image by') . ' ' . $this->userName?></h1>
    <p><?=$this->image->getName()?></p>
    <a href="<?php echo $this->image->getUrl(); ?>" data-lightbox="<?php echo $this->image->getAlias(); ?>"
       title="<?php echo $this->image->getName(); ?>" class="thumbnail">
        <img src="<?php echo $this->image->getThumbUrl() . '_big'; ?>" alt="<?=$this->image->getName()?>">
        <div class="zoom-image">
            <span class="glyphicon glyphicon-search"></span>
        </div>
    </a>
    <p class="text-muted"><?=$this->image->getShortDescription()?></p>
    <div class="fb-like" data-href="<?php echo $this->serverUrl(true); ?>" data-layout="button_count"
         data-action="like" data-show-faces="false" data-share="false">
    </div>

    <div class="fb-comments" data-href="<?php echo $this->serverUrl(true); ?>" data-width="600" data-numposts="10"
         data-colorscheme="dark">
    </div>
</div>