<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('Delete image'); ?></h4>
            </div>
            <div class="modal-body">
                <?= $this->translate('Are you sure you want to delete this image?') ?>
            </div>
            <div class="modal-footer">
                <a href="<?php echo $this->url('admin/adminGallery', array('alias' => '')); ?>"
                   class="btn btn-danger"><?php echo $this->translate('Yes') ?></a>
                <a href="javascript:$('#myModal').modal('hide')" class="btn btn-default"><?php echo $this->translate(
                        'No'
                    ) ?>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="myModalShare" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('Share image'); ?></h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <a href="javascript:$('#myModalShare').modal('hide')" class="btn btn-default"><?php echo $this->translate(
                        'OK'
                    ) ?>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row album-page">
    <h1><?php echo $this->album->getName(); ?></h1>
    <small><?php echo $this->album->getLocation(); ?></small>
    <?php if ($this->album->getLocationLat() && $this->album->getLocationLng() && $this->album->getLocation()) { ?>
        <a href="http://maps.google.com/maps?q=<?=
        $this->album->getLocationLat() . ',' . $this->album->getLocationLng() . '+(' . $this->album->getLocation()
        . ')&z=12' ?>" target="_blank" class="btn btn-info btn-xs">
            <span class="glyphicon glyphicon-map-marker"></span>
        </a>
    <?php } ?>
    <p class="text-muted"><?php echo $this->album->getFullDescription(); ?></p>
    <?php if ($this->isOwner) { ?>
        <div class="upload-images-button-container">
            <a href="<?php echo $this->url(
                'home/gallery/uploadImages', ['alias' => $this->album->getAlias(), 'userName' => $this->userName]
            ); ?>" class="btn btn-success btn-sm admin-add-album">
                <span class="glyphicon glyphicon-plus"></span>
                <?php echo $this->translate('Upload images'); ?>
            </a>
            <?php if (count($this->albumImages) > 1) { ?>
                <a href="<?= $this->albumImages[0]->getUrl() ?>" data-lightbox="album-set"
                   class="btn btn-info btn-sm admin-add-album">
                    <span class="glyphicon glyphicon-new-window"></span>
                    <?php echo $this->translate('View all'); ?>
                </a>
            <?php } ?>
        </div>
    <?php } ?>
    <?php foreach ($this->albumImages as $key => $image) { ?>
        <div class="col-md-3 margin-bottom-25">
            <?php if ($this->isOwner) { ?>
                <a href="<?php echo $this->url(
                    'home/gallery/album/editImage',
                    ['alias' => $album->getAlias(), 'userName' => $this->userName, 'imageAlias' => $image->getAlias()]
                ); ?>"
                   class="btn btn-info btn-xs admin-edit">
                    <span class="text"><?= $this->translate('Edit image'); ?></span>
                    <span class="glyphicon glyphicon-edit"></span>
                </a>
                <a data-toggle="modal" href="#myModal" class="btn btn-danger btn-xs admin-remove remove-item"
                   data-delete-url="<?php echo $this->url(
                       'home/gallery/album/deleteImage', ['alias'     => $album->getAlias(),
                                                         'userName'   => $this->userName,
                                                         'imageAlias' => $image->getAlias()]
                   ); ?>">
                    <span class="text"><?= $this->translate('Remove image'); ?></span>
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
                <a data-toggle="modal" href="#myModalShare" class="btn btn-warning btn-xs share-item"
                   data-share-url="<?php echo $this->url(
                       'home/gallery/album/image',
                       ['alias'   => $this->album->getAlias(), 'imageAlias' => $image->getAlias(),
                       'userName' => $this->userName], ['force_canonical' => true]
                   ); ?>">
                    <span class="text"><?= $this->translate('Share image'); ?></span>
                    <span class="glyphicon glyphicon-share-alt"></span>
                </a>
            <?php } ?>
            <a href="<?php echo $this->url(
                'home/gallery/album/image',
                ['alias' => $this->album->getAlias(), 'imageAlias' => $image->getAlias(), 'userName' => $this->userName]
            ); ?>" class="btn btn-success btn-xs fb-comments-count">
                <div class="text" data-href="<?php echo $this->url(
                    'home/gallery/album/image',
                    ['alias'   => $this->album->getAlias(), 'imageAlias' => $image->getAlias(),
                    'userName' => $this->userName], ['force_canonical' => true]
                ); ?>">0
                </div>
                <span class="glyphicon glyphicon-comment"></span>
            </a>

            <div class="btn btn-primary btn-xs up-vote" data-upvote-url="<?php echo $this->url(
                'home/gallery/album/upVote', ['userName'  => $this->userName, 'alias' => $this->album->getAlias(),
                                             'imageAlias' => $image->getAlias()], ['force_canonical' => true]
            ); ?>">
                <span class="text score"><?php echo $image->getVotesCount(); ?></span>
                <span class="glyphicon glyphicon-plus"></span>
            </div>
            <div class="btn btn-primary btn-xs down-vote" data-downvote-url="<?php echo $this->url(
                'home/gallery/album/downVote', ['userName'  => $this->userName, 'alias' => $this->album->getAlias(),
                                               'imageAlias' => $image->getAlias()], ['force_canonical' => true]
            ); ?>">
                <span class="text score"><?php echo $image->getVotesCount(); ?></span>
                <span class="glyphicon glyphicon-minus"></span>
            </div>
            <a href="<?php echo $this->url(
                'home/gallery/album/image',
                ['alias' => $this->album->getAlias(), 'imageAlias' => $image->getAlias(), 'userName' => $this->userName]
            ); ?>" class="thumbnail">
                <div class="image-info">
                    <h3><?php echo $image->getName(); ?></h3>
                    <p><?php echo $image->getShortDescription(); ?></p>
                    <h6><?=$this->translate('Image by') . ' ' . $image->getAlbum()->getUser()->getUserName()?></h6>
                </div>
                <img src="<?php echo $image->getThumbUrl() . '_cropped'; ?>" alt="<?= $image->getName() ?>">
            </a>
        </div>
    <?php } ?>
</div>
<div class="hidden-links">
    <?php foreach ($this->albumImages as $key => $image) {
        if ($key != 0) {
            ?>
            <a href="<?= $image->getUrl() ?>" data-lightbox="album-set" title="<?= $image->getName() ?>"></a>
        <?php
        }
    } ?>
</div>