<a href="<?php echo $this->image->getUrl(); ?>" data-lightbox="<?php echo $this->image->getAlias(); ?>"
   title="<?php echo $this->image->getName(); ?>">
    <img class="img-thumbnail" src="<?php echo $this->image->getThumbUrl() . '_big'; ?>">
</a>
<div class="fb-comments" data-href="<?php echo $this->serverUrl(true); ?>" data-width="600" data-numposts="10"
     data-colorscheme="light">
</div>
<div class="fb-like" data-href="<?php echo $this->serverUrl(true); ?>" data-layout="button_count"
     data-action="like" data-show-faces="false" data-share="false">
</div>