<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('modal_title'); ?></h4>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <a href="<?php echo $this->url('admin/adminGallery', array('alias' => '')); ?>"
                   class="btn btn-danger"><?php echo $this->translate('yes') ?></a>
                <a href="javascript:$('#myModal').modal('hide')" class="btn btn-default"><?php echo $this->translate(
                        'no'
                    ) ?></a>
            </div>
        </div>
    </div>
</div>
<?php if (!$this->logged) { ?>
    <div class="alert alert-info"><?php echo $this->translate('please_log_in_to_manage_your_gallery'); ?></div>
<?php } else { ?>
    <a href="<?php echo $this->url('home/gallery/addAlbum'); ?>" class="btn btn-success btn-xs admin-add-album">
        <span class="glyphicon glyphicon-plus"><?php echo $this->translate('add_album'); ?></span>
    </a>
    <div class="row">
        <?php if (!$this->galleryAlbums) { ?>
            <div class="alert alert-info"><?php echo $this->translate('no_albums_in_gallery'); ?></div>
        <?php } ?>
        <?php foreach ($this->galleryAlbums as $album) { ?>
            <div class="col-md-3 margin-bottom-25">
                <a href="<?php echo $this->url('home/gallery/editAlbum', ['alias' => $album->getAlias()]); ?>"
                   class="btn btn-info btn-xs admin-edit">
                    <span class="glyphicon glyphicon-edit"></span>
                </a>
                <a data-toggle="modal" href="#myModal" class="btn btn-danger btn-xs admin-remove remove-item"
                   data-delete-url="<?php echo $this->url(
                       'home/gallery/deleteAlbum', array('alias' => $album->getAlias())
                   ); ?>">
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
                <a href="<?php echo $this->url('home/gallery/album', ['alias' => $album->getAlias()]) ?>"
                   class="thumbnail">
                    <img alt="...">

                    <div class="caption">
                        <h3><?php echo $album->getName(); ?></h3>

                        <p><?php echo $album->getShortDescription(); ?></p>
                    </div>
                </a>
            </div>
        <?php } ?>
    </div>
<?php } ?>