<?php if ($this->isAdmin) { ?>
    <a href="<?php echo $this->url('admin/adminGallery/addAlbum'); ?>" class="btn btn-success btn-xs admin-add-album">
        <span class="glyphicon glyphicon-plus"><?php echo $this->translate('add_album'); ?></span>
    </a>
<?php } ?>
<div class="row">
    <?php if (!$this->galleryAlbums) { ?>
        <div class="alert alert-info"><?php echo $this->translate('no_albums_in_gallery'); ?></div>
    <?php } ?>
    <?php foreach ($this->galleryAlbums as $album) { ?>
        <div class="col-md-3 margin-bottom-25">
            <?php if ($this->isAdmin) { ?>
                <a href="#" class="btn btn-info btn-xs admin-edit">
                    <span class="glyphicon glyphicon-edit"></span>
                </a>
                <a href="#" class="btn btn-danger btn-xs admin-remove">
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
            <?php } ?>
            <a href="<?php echo $this->url('home/gallery/album', ['alias' => $album->getAlias()]) ?>" class="thumbnail">
                <img alt="...">
                <div class="caption">
                    <h3><?php echo $album->getName(); ?></h3>
                    <p><?php echo $album->getShortDescription(); ?></p>
                </div>
            </a>
        </div>
    <?php } ?>
</div>