<div class="row">
    <div class="well">
        <?php
        if ($this->error) {
            echo $this->error;
        }
        if ($this->uploadImageForm) {
            $form = $this->uploadImageForm;
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formCollection($form);
            echo $this->form()->closeTag($form);
        }
        ?>
    </div>
</div>

